name: Cypress Tests

on:
  push:
    branches:
      - main
      - production
      - staging
  pull_request:
    branches:
      - main
      - production
      - staging

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.2
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: todo_testing
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        with:
          record: true
          working-directory: ./client
          build: npm run build
          start: |
            npm start
            npm run start-test-backend
          wait-on: 'http://localhost:3000, http://localhost:8080/health-check'
