name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
        with:
          working-directory: ./client
          build: npm run build
          start: npm start
      - name: Save screenshots on failure
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: client/cypress/screenshots
      - name: Save video
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: client/cypress/videos
