name: Cypress Tests

on:
  push:
    branches:
      - main
      - production
      - staging
    pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        with:
          record: true
          working-directory: ./client
          build: npm run build
          start: npm start
