# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Deploy Backend to Elastic Beanstalk

on:
  push:
    branches:
      - staging
      
defaults:
  run:
    working-directory: server

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.2
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: todo
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build and test with Maven
      run: ./mvnw spring-boot:build-image -Dspring.profiles.active=staging
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v16
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ToDoBackend
        environment_name: ToDoBackend-dev
        region: us-west-1
        deployment_package: target/todoapi-0.0.1-SNAPSHOT.jar
